name: Deploy Hugo Profiles site to GitHub Pages

on:
  push:
    branches:
      - main  # runs on every push to main

permissions:
  contents: write   # required to push to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.152.2'  # match your local extended version
          extended: true

      - name: Build site
        run: hugo --minify

      #- name: Deploy to GitHub Pages
       # uses: peaceiris/actions-gh-pages@v4
       # with:
        #  github_token: ${{ secrets.GITHUB_TOKEN }}
        #  publish_dir: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
